import {
    CutlassText,
    HorizontalDivider,
    PanelBase,
    CutlassScrollView,
    VerticalDivider,
} from "../../components/index.slint";
import { AppStore } from "../../store/index.slint";
import { Toolbar } from "toolbar.slint";
import { TrackLane } from "track-lane.slint";
import { TrackHead } from "track-head.slint";
import { Ruler } from "ruler.slint";
import { TimelineState } from "state.slint";



    component ForceHeadSpace inherits Rectangle {
    property <length> force-head-space: 50px;

    height: force-head-space;
    background: transparent;
}

export component TimelinePanel inherits PanelBase {
    private property <int> track-count: 10;
    private property <length> track-spacing: AppStore.theme.metrics.spacing.sm;
    VerticalLayout {

        spacing: AppStore.theme.metrics.spacing.none;

        Toolbar {
            height: AppStore.theme.metrics.layout.toolbar-height;
        }

        Ruler { }

        HorizontalLayout {

            spacing: 60px;

            Flickable {
                viewport-y <=> TimelineState.scroll-y;
                height: 100%;
                width: 100px;

                VerticalLayout {

                    spacing: track-spacing;
                    vertical-stretch: 1;

                    ForceHeadSpace { }

                    for i in track-count: TrackHead { }
                }

                VerticalDivider {
                    x: parent.width - self.width;
                    width: AppStore.theme.metrics.stroke.thin;
                }
            }

            Flickable {
                viewport-width: 1000000px;
                viewport-y <=> TimelineState.scroll-y;
                viewport-x <=> TimelineState.scroll-x;

                VerticalLayout {
                    spacing: track-spacing;

                    vertical-stretch: 1;
                    horizontal-stretch: 1;

                    ForceHeadSpace { }

                    for _ in track-count: TrackLane {
                        for c in 10: Rectangle {

                            x: c * 220px;
                            height: 58px;
                            width: 200px;
                            background: #373737;
                        }
                    }
                }
            }
        }
    }
}
