import { PanelBase, PanelHeader } from "../../components/index.slint";
import { AppStore } from "../../store/index.slint";

export component PreviewPanel inherits PanelBase {
    VerticalLayout {
        PanelHeader {
            title: "Preview";
        }

        // padding: AppStore.theme.metrics.spacing.xxl;
        spacing: AppStore.theme.metrics.spacing.none;

        Rectangle {
            vertical-stretch: 1;
            horizontal-stretch: 1;
            background: AppStore.theme.surface.content-background;
        }
    }
}
