import { PanelBase } from "../../components/panel-base.slint";
import { AppStore } from "../../store/app-store.slint";

export component PreviewPanel inherits PanelBase {
    VerticalLayout {
        padding: AppStore.theme.metrics.spacing.xxl;
        spacing: AppStore.theme.metrics.spacing.none;

        Rectangle {
            vertical-stretch: 1;
            horizontal-stretch: 1;
            background: AppStore.theme.surface.content-background;
        }
    }
}
