
import { TimelineState } from "./state.slint";

export component PlayHead inherits Rectangle {

    in property <length> head-height: 16px;
    in property <length> head-radius: 3px;
    in property <length> head-bottom-radius: 6px;
    in property <length> head-stroke-width: 1.5px;

    in property <length> line-width: 1.2px;
    in property <brush> playhead-color: #ffffff;
    width: TimelineState.playhead-width;
    background: transparent;

    head := Rectangle {
        y: 0;
        x: (TimelineState.playhead-width - TimelineState.playhead-head-width) / 2;
        width: TimelineState.playhead-head-width;
        height: head-height;

        border-top-left-radius: head-radius;
        border-top-right-radius: head-radius;
        border-bottom-left-radius: head-bottom-radius;
        border-bottom-right-radius: head-bottom-radius;

        background: transparent;
        border-width: head-stroke-width;
        border-color: root.playhead-color;
    }

    Rectangle {
        y: head-height;
        width: line-width;
        height: parent.height - head-height;
        background: root.playhead-color;
    }

    ta := TouchArea {
        width: 100%;
        height: 100%;
        mouse-cursor: MouseCursor.ew-resize;

        property <length> drag-start-playhead-x;
        property <length> drag-origin-root-x;

        pointer-event(event) => {
            if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                self.drag-start-playhead-x = TimelineState.playhead-x;
                self.drag-origin-root-x = self.absolute-position.x + self.pressed-x;
            }
        }

        moved() => {
            if (!self.pressed) {
                return;
            }
            let drag-distance = self.drag-start-playhead-x + self.absolute-position.x + self.mouse-x - self.drag-origin-root-x;
            TimelineState.playhead-x = max(0px, min(TimelineState.viewport-width, drag-distance));
        }
    }
}
