
import { TimelineState } from "./state.slint";

export component Ruler inherits Rectangle {
    height: 24px;
    background: #4646b6;

    property <length> minor-spacing: 20px;
    property <int> major-every: 5;
    property <int> tick-count: max(1, ceil(self.width / minor-spacing));

    for idx in tick-count: Rectangle {
        property <bool> major: mod(idx, major-every) == 0;
        x: idx * minor-spacing;
        y: 2px;
        width: major ? 1.2px : 1px;
        height: major ? 12px : 6px;
        background: major ? #5b5b5b : #464646;
    }

    for idx in tick-count: Text {
        visible: mod(idx, major-every) == 0;
        x: idx * minor-spacing + 5px;
        y: 3.5px;
        text: "\{idx / major-every}";
        color: #5b5b5b;
        font-size: 9px;
        font-weight: 700;
    }

    ta := TouchArea {
        width: 100%;
        height: 100%;

        property <length> drag-start-playhead-x;
        property <length> drag-origin-root-x;

        pointer-event(event) => {
            if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                TimelineState.playhead-x = min(TimelineState.viewport-width, self.pressed-x);
                self.drag-start-playhead-x = TimelineState.playhead-x;
                self.drag-origin-root-x = self.absolute-position.x + self.pressed-x;
            }
        }

        moved() => {
            if (!self.pressed) {
                return;
            }
            let drag-distance = self.drag-start-playhead-x + self.absolute-position.x + self.mouse-x - self.drag-origin-root-x;
            TimelineState.playhead-x = max(0px, min(TimelineState.viewport-width, drag-distance));
        }
    }
}
