export global TimelineState {
    in-out property <length> ruler-offset: 10px;
    in-out property <int> zoom-step: 1;
    in-out property <float> zoom: 50.0;
    in-out property <length> scroll-y: 0px;
    in-out property <length> scroll-x: 0px;
    in-out property <length> ruler-height: 24px;
    in-out property <length> playhead-x: 160px;
    in-out property <length> playhead-head-width: 12px;
    in-out property <length> playhead-width: 1.5px;

    in-out property <length> viewport-width: 10300px;
    in-out property <length> viewport-height: 400px;
}
