// Bottom timeline region (height comes from parent `timeline-height`).

import { Ruler } from "./ruler.slint";
import { TimelineState } from "./state.slint";
import { Toolbar } from "./toolbar.slint";
import { PlayHead } from "./playhead.slint";
import { HorizontalDivider, VerticalDivider } from "../divider.slint";



export component TimelinePanel inherits Rectangle {
    horizontal-stretch: 1;
    background: #28282a;

    VerticalLayout {
        width: 100%;
        height: 100%;
        spacing: 0px;

        Toolbar { }

        HorizontalDivider { }

        HorizontalLayout {
            spacing: 50px;

            VerticalLayout {
                Rectangle {
                    height: TimelineState.ruler-height;
                }

                track-action := Flickable {
                    vertical-stretch: 1;
                    horizontal-stretch: 1;
                    viewport-y <=> TimelineState.scroll-y;

                    width: 200px;
                    viewport-height: TimelineState.viewport-height;

                    interactive: false;
                    VerticalLayout {
                        spacing: 10px;
                        for tdx in 10: Rectangle {
                            height: 60px;
                            width: 100%;
                            background: #1b1b1b;
                        }
                    }
                }
            }

            Rectangle {
                clip: true;
                horizontal-stretch: 1;
                height: 100%;

                VerticalLayout {
                    width: 100%;
                    height: 100%;

                    Ruler {
                        height: TimelineState.ruler-height;
                        x: tracks.viewport-x;
                    }

                    tracks := Flickable {

                        vertical-stretch: 1;
                        horizontal-stretch: 1;

                        viewport-y <=> TimelineState.scroll-y;
                        viewport-x <=> TimelineState.scroll-x;

                        viewport-width: TimelineState.viewport-width;
                        viewport-height: TimelineState.viewport-height;

                        interactive: false;

                        VerticalLayout {
                            spacing: 10px;
                            for tdx in 10: Rectangle {
                                height: 60px;
                                width: 100%;
                                background: #1b1b1b;

                                for cdx in 5: Rectangle {
                                    height: parent.height - 10px;
                                    width: 300px;
                                    background: #46469d;
                                    x: cdx * (300px + 20px);
                                }
                            }
                        }
                    }
                }

                PlayHead {
                    y: 0;
                    height: parent.height;
                    x: TimelineState.playhead-x + tracks.viewport-x;
                }
            }
        }
    }
}
