import {
    CutlassText,
    HSplitGripLead,
    HSplitGripTrail,
    VSplitGripTimeline,
} from "components/index.slint";
import {
    InspectorPanel,
    LibraryPanel,
    PreviewPanel,
    TimelinePanel,
} from "panels/index.slint";
import { AppStore } from "store/index.slint";

export component AppWindow inherits Window {
    title: "Hello World";

    preferred-width: 1280px;
    preferred-height: 800px;

    default-font-size: AppStore.theme.typography.body.size;
    default-font-weight: AppStore.theme.typography.body.weight;

    in-out property <length> left-pane-width: 350px;
    in-out property <length> right-pane-width: 350px;
    in-out property <length> timeline-height: 400px;

    background: AppStore.theme.surface.app-background;

    VerticalLayout {
        padding: AppStore.theme.metrics.spacing.sm;
        spacing: AppStore.theme.metrics.spacing.none;
        Rectangle {
            height: 40px;
            background: AppStore.theme.surface.app-background;
            CutlassText {
                text: "Cutlass Head";
                style: AppStore.theme.typography.label;
            }
        }

        HorizontalLayout {
            vertical-stretch: 1;
            horizontal-stretch: 1;
            spacing: AppStore.theme.metrics.spacing.none;

            LibraryPanel {
                width: root.left-pane-width;
                vertical-stretch: 1;
            }

            HSplitGripLead {
                pane-width <=> root.left-pane-width;
                vertical-stretch: 1;
            }

            PreviewPanel {
                vertical-stretch: 1;
                horizontal-stretch: 1;
            }

            HSplitGripTrail {
                pane-width <=> root.right-pane-width;
                vertical-stretch: 1;
            }

            InspectorPanel {
                width: root.right-pane-width;
                vertical-stretch: 1;
            }
        }

        VSplitGripTimeline {
            timeline-height <=> root.timeline-height;
        }

        TimelinePanel {
            height: root.timeline-height;
            horizontal-stretch: 1;
        }
    }
}
